# Array Slicing and Spliting and Boolean 

In [51]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b = np.array([[[7,8,9],[6,5,4],[3,2,1]]])

#ndim
print("Dimension of a is: ",a.ndim)

print("Dimension of b is: ",b.ndim)

print("\n\nMetrix a is: \n",a)
print("\n\nMetrix b is: \n",b)

#itemsize
print("\n\n",a.itemsize)

#dtype

print("\n\n",a.dtype)


Dimension of a is:  3
Dimension of b is:  3


Metrix a is: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Metrix b is: 
 [[[7 8 9]
  [6 5 4]
  [3 2 1]]]


 4


 int32


In [2]:
import numpy as np
simple_list = [6,7,8]
print(simple_list[0:2])


print(simple_list[-1])

# Similarly indexing with array
a = np.array([6,7,8])
print("Array value: ",a[0:2])
print(a[-1])


[6, 7]
8
Array value:  [6 7]
8


In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print("\n\n",arr[0:2])
print("\n",arr[0])
print("\n",arr[-1])
print("\n\n",arr[0:2,2])  #gives the 2 indexing element of row 0th and 1th
print("\n\n",arr[1,2])     # row 1th and element 2 maens(6)  (0th,1th,2th)
print("\n\n",arr[-1,0:2]) #means last row and element is from 0 to 1 and 2 is discarded
print("\n\n",arr[:,1:3])  # for printing last two columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 [[1 2 3]
 [4 5 6]]

 [1 2 3]

 [7 8 9]


 [3 6]


 6


 [7 8]


 [[2 3]
 [5 6]
 [8 9]]


In [13]:
#using loop
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(a)

for row in a:
    print(row)  # for printing each row
    
print("\n\nElenemt of matrix is: ")   
for cell in a.flat:
    print("\n\n",cell)  # for printing each element of matrix 
    
    

[1 2 3]
[4 5 6]
[7 8 9]


Elenemt of matrix is: 


 1


 2


 3


 4


 5


 6


 7


 8


 9


In [22]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print("\n\n",b)

print("\n\n",np.vstack((a,b)))  # put both matrix together in a stack OR vertical stacking
print("\n\n",np.hstack((a,b)))  # stacking two array in horizontal



[[0 1]
 [2 3]
 [4 5]]


 [[ 6  7]
 [ 8  9]
 [10 11]]


 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [37]:
a = np.arange(30).reshape(2,15)
print(a)
res=np.hsplit(a,3)
print("\n\n",res)
print("\n\n",res[0])
print("\n\n",res[1])
print("\n\n",res[2])
res1 = np.vsplit(a,2)
print("\n\n",res1)
print("\n\n",res1[0])

print("\n\n",res1[1])

# print("\n\n",res1[2])  out of range

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


 [array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


 [[ 0  1  2  3  4]
 [15 16 17 18 19]]


 [[ 5  6  7  8  9]
 [20 21 22 23 24]]


 [[10 11 12 13 14]
 [25 26 27 28 29]]


 [array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


 [[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [50]:
# Boolean operation
a = np.arange(12).reshape(3,4)
print(a)
b=a>4
print("\n\n",b)
# b
print("\n\n",a[b])  #it will give all tha value which is true for b

a[b]=-1  # Here those numbers which is greater than 4 is replaced by -1 
print("\n\n",a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


 [ 5  6  7  8  9 10 11]


 [[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
