In [2]:
# reverse a array in numpy
# Ques: Print the reverse NumPy array with type float.
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    numpy_arr = numpy.array(arr,float)
    return numpy_arr

    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

12 5 8 32 4 65
[65.  4. 32.  8.  5. 12.]


In [3]:
# You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

num_arr = numpy.array([1,2,3,4,5,6,7,8,9])
print(numpy.reshape(num_arr,(3,3)))
# import numpy as np
# print(np.array(input().split(),int).reshape(3,3))


# num_arr = numpy.array(input().split(),int).reshape(3,3)
# print(num_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# You are given a X integer array matrix with space separated elements ( = rows and  = columns).
# Your task is to print the transpose and flatten results.

num_arr = numpy.array(input().split(),int)
print(num_arr.transpose())

1 2 2 4 1 3
[1 2 2 4 1 3]


In [7]:
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print( numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [8]:
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(my_array.flatten())


[1 2 3 4 5 6]


In [12]:
my_array = numpy.array([[1,2,3],
                      [4,5,6]])
x = numpy.transpose(my_array)
print(x)
y = numpy.flatten()
print(y)

[[1 4]
 [2 5]
 [3 6]]


AttributeError: module 'numpy' has no attribute 'flatten'