# Numpy


* Numpy is extremely popular python module. It is heavily used in Science Computing.
* For installation use:  "pip install numpy"
* Numpy's most useful feature is n dimentional array object (a.k.a ndarray)

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [3]:
print(a[0])
print(a[1])
print(a[2])
#a[3]  #out of range gives IndexError

1
2
3


* Question: In pyhton there is already list then why we use numpy array ??

Answer: There are three main benefits of numpy array over a python list: 
* (1) Less Memory 
* (2) Fast 
* (3) Convinient

In [4]:
# Less memory
import numpy as np
import sys

print(sys.version) # for getting the version of sys

l = range(1000)
print(sys.getsizeof(1)*len(l))  # take 28 bytes of memory means 1 element = 28 bytes

array = np.arange(1000)
print(array.size * array.itemsize) # 1 element = 4 bytes 
#here array.size gives total length of array and array.itemsize gives the size of single element

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
28000
4000


In [5]:
# Fast 
# We will use two list of numbers using python list and numpy array and compare them 

import time

Size = 1000000

l1 = range(Size)
l2 = range(Size)

a1 = np.arange(Size)
a2 = np.arange(Size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took time: ",(time.time()-start)*1000) #by defult time in seconds so we put 1000 here for miliseconds

# numpy array
start = time.time()
result = a1 + a2 #covinient because when we add two array we simply write a1+a2 
print("Numpy took time: ",(time.time()-start)*1000)

Python list took time:  405.3511619567871
Numpy took time:  24.56808090209961


In [6]:
# Convinient
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1+a2)

print(a2-a1)

print(a1*a2)

print(a1/a2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# Basic Array Operations

* ndim
* itemsize
* dtype
* size
* shape
* zeros
* ones
* arange
* linspace
* reshape
* ravel
* min
* max
* sum
* axis=0
* axis=1
* sqrt
* sdt
* dot


In [7]:
# ndim
import numpy as np
a = np.array([5,6,7])  #one dimensional array
print("1-D Array: \n",a)

b = np.array([[1,2],[3,4],[5,6]])
print("\n\n2-D Array:\n",b)


print(a.ndim)  #it tells the dimension of metrix
print(b.ndim)  


1-D Array: 
 [5 6 7]


2-D Array:
 [[1 2]
 [3 4]
 [5 6]]
1
2


In [8]:
# itemsize
import numpy as np
a = np.array([5,6,7])
print(a.itemsize)  #it tells the size of a single element
# There is integer that why the here the size is bytes 

b = np.array([[1,2],[3,4],[5,6]])
print("\n\n2-D Array:\n",b)
print(b.itemsize)


4


2-D Array:
 [[1 2]
 [3 4]
 [5 6]]
4


In [9]:
# dtype
a = np.array([1,2,3])
print(a.dtype)  # it tells the data type of array
print('Bytes used: ',a.itemsize)

x = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)  # it can change the datatype 
print(x)
print("Bytes used: ",x.itemsize)
x


int32
Bytes used:  4
[[1. 2.]
 [3. 4.]
 [5. 6.]]
Bytes used:  8


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [59]:
# size
x = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(x)
x.size # total number of element present in array

[[1. 2.]
 [3. 4.]
 [5. 6.]]


6

In [62]:
# shape 
x = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(x)
x.shape  # gives the shape of matrix i.e width and height(rows,column)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


(3, 2)

In [64]:
x = np.array([[1,2],[3,4],[5,6]], dtype=complex)
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [65]:
# Sometime we want to initialize array with zeros then we use zeros
# we simply write np.zeros( (shape) )
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
# initialize matrix with ones
np.ones( (3,5) )

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
# arange it is similar to range function in list
l=range(5)
print(l)
print(l[0])
print(l[1])
print(l[2])

#similarly 
print(np.arange(1,5)) # it gives array according to given range
print(np.arange(1,5,2)) #steps jump

range(0, 5)
0
1
2
[1 2 3 4]
[1 3]


In [83]:
#linspace
print(np.linspace(1,5,10)) # it will generate 10 numbers which is linearly space
print("\n\n", np.linspace(1,5,5))
print("\n\n",np.linspace(1,5,20))


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


 [1. 2. 3. 4. 5.]


 [1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [98]:
# reshape
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("\n",a.shape)

print("\n\n",a.reshape(2,3))


a.reshape(6,1)

[[1 2]
 [3 4]
 [5 6]]

 (3, 2)


 [[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [104]:
#ravel
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print("\n\n",a.ravel()) # it will flatten the array or make it one dimension
print("\n\n",a)  #ravel don't change original array it will just return a new array


[[1 2]
 [3 4]
 [5 6]]


 [1 2 3 4 5 6]


 [[1 2]
 [3 4]
 [5 6]]


In [106]:
#min
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("\n\n",a.min())

[[1 2]
 [3 4]
 [5 6]]


 1


In [107]:
#max
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("\n\n",a.max())

[[1 2]
 [3 4]
 [5 6]]


 6


In [108]:
# axis=0 deal with  column value
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a.sum(axis=0)


[[1 2]
 [3 4]
 [5 6]]


array([ 9, 12])

In [7]:
# axis=1 deal with  each row value
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a.sum(axis=1)


[[1 2]
 [3 4]
 [5 6]]


array([ 3,  7, 11])

In [6]:
#sum
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a.sum()

[[1 2]
 [3 4]
 [5 6]]


21

In [8]:
#sqrt
a = np.array([[1,2],[3,4],[5,6]])
print(a)
np.sqrt(a)


[[1 2]
 [3 4]
 [5 6]]


array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [9]:
#std (standard deviation)
a = np.array([[1,2],[3,4],[5,6]])
print(a)
np.std(a)


[[1 2]
 [3 4]
 [5 6]]


1.707825127659933

In [13]:
#Some array operation
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print("\n\n",b)
print("\n\n",a+b)
print("\n\n",a-b)
print("\n\n",a*b)
print("\n\n",a/b)

[[1 2]
 [3 4]]


 [[5 6]
 [7 8]]


 [[ 6  8]
 [10 12]]


 [[-4 -4]
 [-4 -4]]


 [[ 5 12]
 [21 32]]


 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
#a.dot(b)
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print("\n\n",b)
print("\n\n",a.dot(b))  #matrix product

[[1 2]
 [3 4]]


 [[5 6]
 [7 8]]


 [[19 22]
 [43 50]]
